### ISSUE TITLE
"share chart" from "Other tools" is broken

### ISSUE THREAD

**Issue by felix9** [Devographics/Monorepo#391] opened 2024-06-22 11:21 UTC
on this page https://2023.stateofjs.com/en-US/other-tools/
- click on a "share chart" link
- click on "copy url"
- paste the copied url into a browser
- after redirect, I end up at a 404 page, url is something like https://2023.stateofjs.com/en-US/other_tools/#libraries

cause: typo "other_tools" should be "other-tools"

**Comment by SachaG** [comment] 2024-06-22 20:59
Duplicate of https://github.com/Devographics/Monorepo/issues/380, fixed for now

**Closed by SachaG** 2024-06-22 20:59 UTC
